# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./diff_match_patch.h \
    ./diff_match_patch_test.h
SOURCES += ./diff_match_patch.cpp \
    ./diff_match_patch_test.cpp
